name: CI for Node.js application

on:
  push:
    branches: [ main,dev ]
  pull_request:
    branches: [ main,dev ]
  release:
    types: [created]

env:
  IMAGE_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || github.sha }}

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Frontend Compilation (Syntax Check)
        run: |
          cd client
          npm install
          npm run build

      - name: Backend Compilation (Syntax Check)
        run: |
          cd api
          find . -name "*.js" -exec node --check {} \;
  
  gitleaks-scan:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Gitleaks Scan
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1

  trivy_fs_scan:
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner (FS)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
          # To fail the job when vulnerabilities are found, Add below line
          # exit-code: 1

  build_backend_docker_image:
    runs-on: ubuntu-latest
    needs: trivy_fs_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image (backend)
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: false
          load: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/3-tier-backend:latest
            ${{ vars.DOCKERHUB_USERNAME }}/3-tier-backend:${{ env.IMAGE_TAG }}

  build_frontend_docker_image:
    runs-on: ubuntu-latest
    needs: trivy_fs_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image (frontend)
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: false
          load: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/3-tier-frontend:latest
            ${{ vars.DOCKERHUB_USERNAME }}/3-tier-frontend:${{ env.IMAGE_TAG }}

  trivy_image_scan:
    runs-on: ubuntu-latest
    needs:
      - build_backend_docker_image
      - build_frontend_docker_image
    steps:
      - name: Checkout (noop, keeps workspace consistent)
        uses: actions/checkout@v4

      - name: Run Trivy image scan for backend
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/3-tier-backend:${{ env.IMAGE_TAG }}
          format: table
          exit-code: '0'                 # set to '1' to fail on vulns
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Run Trivy image scan for frontend
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/3-tier-frontend:${{ env.IMAGE_TAG }}
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

  push_docker_images:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs:
      - build_backend_docker_image
      - build_frontend_docker_image
    env:
      IMAGE_TAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Retag and push backend image
        run: |
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/3-tier-backend:latest \
                      ${{ vars.DOCKERHUB_USERNAME }}/3-tier-backend:${{ env.IMAGE_TAG }}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/3-tier-backend:${{ env.IMAGE_TAG }}

      - name: Retag and push frontend image
        run: |
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/3-tier-frontend:latest \
                      ${{ vars.DOCKERHUB_USERNAME }}/3-tier-frontend:${{ env.IMAGE_TAG }}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/3-tier-frontend:${{ env.IMAGE_TAG }}


  update_cd_repo:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' 
    needs: push_docker_images
    steps:
      - name: Determine CD branch and environment folder
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "branch=main" >> $GITHUB_OUTPUT
            echo "env_folder=k8s-prod" >> $GITHUB_OUTPUT
          else
            echo "branch=dev" >> $GITHUB_OUTPUT
            echo "env_folder=k8s-dev" >> $GITHUB_OUTPUT
          fi

      - name: Checkout CD repo
        uses: actions/checkout@v4
        with:
          repository: dhanushKottary/3-Tier-GitOps-CD
          ref: ${{ steps.vars.outputs.branch }}
          token: ${{ secrets.CD_REPO_TOKEN }}
          path: cd

      - name: Bump images in manifests (safe)
        working-directory: cd
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          ENV_FOLDER: ${{ steps.vars.outputs.env_folder }}
        run: |
          curl -sL https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o yq && sudo install yq /usr/local/bin/yq

          # -- Safety cleanup: remove any accidental .spec.template from Service docs
          yq -i '(. | select(.kind=="Service")) |= del(.spec.template)' ${ENV_FOLDER}/backend.yaml
          yq -i '(. | select(.kind=="Service")) |= del(.spec.template)' ${ENV_FOLDER}/frontend.yaml

          # -- Update ONLY Deployment images (backend)
          yq -i '
            (. | select(.kind=="Deployment")
               | .spec.template.spec.containers[]
               | select(.name=="backend")
               | .image)
            = strenv(DOCKERHUB_USERNAME) + "/3-tier-backend:" + strenv(IMAGE_TAG)
          ' ${ENV_FOLDER}/backend.yaml

          # -- Update ONLY Deployment images (frontend)
          yq -i '
            (. | select(.kind=="Deployment")
               | .spec.template.spec.containers[]
               | select(.name=="frontend")
               | .image)
            = strenv(DOCKERHUB_USERNAME) + "/3-tier-frontend:" + strenv(IMAGE_TAG)
          ' ${ENV_FOLDER}/frontend.yaml

          sudo rm yq

      - name: Commit & push to CD repo
        working-directory: cd
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add -A
          git commit -m "bump images to ${IMAGE_TAG} for ${GITHUB_REF_NAME}" || echo "no changes"
          git push origin ${{ steps.vars.outputs.branch }}